{% set name = "scikit-surprise" %}
{% set version = "1.1rc0" %}
{% set sha256 = "75aa9e809be180cd7310fca8b5f31c0357fdb096daed1ba697cf548ebb3b6210" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - cython
    - numpy 1.11.*
  run:
    - setuptools
    - python
    - numpy >=1.11
    - joblib
    - six

test:
  imports:
    - surprise
    - surprise.prediction_algorithms
    - surprise.similarities
    - surprise.dataset
    - surprise.evaluate
    - surprise.model_selection

about:
  home: http://surpriselib.com
  license: BSD-3-Clause
  license_family: BSD
  summary: 'A Python scikit for building and analyzing recommender systems.'

  description:
  doc_url: http://surprise.readthedocs.io/en/stable/
  dev_url: https://github.com/NicolasHug/Surprise

extra:
  recipe-maintainers:
    - NicolasHug
