{% set name = "scikit-surprise" %}
{% set version = "1.1.4" %}
{% set sha256 = "130c45feaee9de4b8cba0aff413ad9b51b2d5c5c90d41aee4759e00059913752" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit_surprise-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - cython
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - joblib
    - scipy

test:
  imports:
    - surprise
    - surprise.prediction_algorithms
    - surprise.similarities
    - surprise.dataset
    - surprise.model_selection

about:
  home: http://surpriselib.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'A Python scikit for building and analyzing recommender systems.'

  description:
  doc_url: http://surprise.readthedocs.io/en/stable/
  dev_url: https://github.com/NicolasHug/Surprise

extra:
  recipe-maintainers:
    - NicolasHug
